### PR TITLE
style(Button): Adjust minimum widths.

### PR DESCRIPTION
**Pull request by schillerk**
to: @milesj @stefhatcher @hayes @alecklandgraf

## Description
This reduces min-width on each of the button sizes and removes the golden ratio calculation.

Values were previously:
52, 78, 104
Screen Shot 2019-07-11 at 11 40 04 AM

Values are now:
48, 64, 72
Screen Shot 2019-07-11 at 11 39 55 AM

## Motivation and Context
See discussion between @adamirl and @kenchendesign in #dls-for-internaltools

## Checklist

- My code follows the style guide of this project.
- I have updated or added documentation accordingly.
- I have read the CONTRIBUTING document.

### CODE REVIEW

**Comment by schillerk** [comment]
Going to wait for https://github.com/airbnb/lunar/pull/117 to land before updating tests.
Will probably be rewriting Button tests for
https://github.com/airbnb/lunar/pull/113#pullrequestreview-260867874 anyway

**Comment by milesj** [comment]
I kind of like the golden ratio. Why not just lower the unit value used with the ratio?

**Comment by schillerk** [comment]
@milesj Yeah, I would have liked to preserve it too, but then we end up with
48 / (1.618 * 8) = 3.7
64 / (1.618 * 8) = 4.94
72 / (1.618 * 8) = 5.56

So we could make 64 work (5 * 1.6 * 8), but

`small` would have to be ~51 (4 * 1.6 * 8) or 38 (3 * 1.6 * 8) and

`large` would have to be ~77 (6 * 1.6 * 8)

@kenchendesign ?

**Comment by kenchendesign** [comment]
I don’t think the golden ratio is meaningful anymore if you need to add
another multiplier.

**Comment by milesj** [comment]
What is the importance of 48, 64, and 72?

**Comment by kenchendesign** [comment]
I guess they are just nice numbers that are multiples of 8. And they
buttons look visually balanced in our experiments.

Yeah I agree it’s all subjective and I’m sure 60 would look good if 64
does. The bottom line is, since the rest of the UIs are based on multiples
of 4 so we should do 64 rather than 62. Beyond that it’s just visual
preference. We already got agreement from multiple designers on the
internal channel so I would recommend those numbers.

**Pull request merged**
