### PR TITLE
fix(Proofreader): Default prop value to empty string

### PR DESCRIPTION
**Pull request by alecklandgraf**
to: @milesj @stefhatcher @hayes @alecklandgraf

## Description

Fix a case where `prevProps.value` is `undefined`.

## Motivation and Context

image

## Testing

Added test

## Screenshots

n/a

## Checklist

- My code follows the style guide of this project.
- I have updated or added documentation accordingly.
- I have read the CONTRIBUTING document.

### CODE REVIEW

**Comment by milesj** [comment]
The value comes from the parent `TextArea`. How is that value undefined?

**Comment by alecklandgraf** [comment]
> The value comes from the parent `TextArea`. How is that value undefined?

It can be undefined because the prop `value` is passed in this chain `TextArea -> Proofreader -> BaseTextArea` and while `BaseTextArea` sets a defaultProp for `value`, `TextArea` doesn't.

**Comment by milesj** [comment]
@alecklandgraf Maybe update them all with a default to be safe.

**Comment by alecklandgraf** [comment]
@milesj updated!

**Pull request merged**
