### PR TITLE
Adding optional size property for checkbox

### PR DESCRIPTION
**Pull request by MarkKahn**
to: @milesj @stefhatcher @hayes @alecklandgraf

## Description

Adds an optional size prop to checkboxes

## Motivation and Context

Need a larger checkbox per design

## Checklist

- My code follows the style guide of this project.
- I have updated or added documentation accordingly.
- I have read the CONTRIBUTING document.

### CODE REVIEW

**Comment by milesj** [comment]
Do you have a screenshot of the design? This seems very arbitrary and unnecessary.

**Comment by stefhatcher** [comment]
Agreed, this seems unnecessary. To keep the design system consistent, I would vote no on this approach. If design would like a larger checkbox, we should also add large radios and inputs that scale the same way as large buttons for consistency. Or if design is heading towards a future iteration where checkboxes and radios are larger, we'd make that the new default.

**Comment by MarkKahn** [comment]
Screen Shot 2019-05-03 at 11 44 33 AM

Thoughts on how else to accomplish this then?

**Comment by milesj** [comment]
Closing this for now.

**Pull request closed without merging**
