### PR TITLE
style(Input, Button, MenuItem): Match padding to design specs

### PR DESCRIPTION
**Pull request by williaster**
to: @milesj @stefhatcher
cc: @elibrumbaugh

## Description

This PR updates the `Input` and `Menu.Item` to match design and implementation of `Input` and `Row` `Item` padding (and closes #763 in `solar`). It specifically
- decreases `Input` left/right padding from `16px` to `12px` , to match the design spec
- increases `Menu.Item` left/right padding from `8px` to `12px`, to match the design spec (note the original design issue #763 refers to `Autocomplete` items, which are implemented with `Menu.Item`)

**UPDATE**
This also makes the following updates to `Button`, to match the changes to `Input`:
- `small` ~`12, 6`~ => `10, 6` (left/right, top/bottom)
- `regular` ~`16, 10`~ => `12, 10` (now matches default `Input`)
- `large` `20, 12` (no change) 

## Motivation and Context

Design and implementation ideally match ✨ 

## Testing

Functionally verified with style guide.

#### `Input`
**Before**
image

**After**
image

#### `MenuItem`
**Before**
image

**After**
image

## Checklist

- My code follows the style guide of this project.
- I have updated or added documentation accordingly.
- I have read the CONTRIBUTING document.

### CODE REVIEW

**Comment by stefhatcher** [comment]
PR title formatting has changed: https://github.com/airbnb/lunar/blob/master/.github/CONTRIBUTING.md#release-prefixes

**Comment by stefhatcher** [comment]
regular buttons also have the 16px padding on the sides. should those be updated to 12px too for consistency, @milesj  ?

https://github.com/airbnb/lunar/blob/master/packages/core/src/themes/buildTheme.ts#L116

**Comment by milesj** [comment]
Ideally everything is consistent IMO.

**Comment by williaster** [comment]
Ah, I see what you meant previously now. Made the change to update button, to clarify buttons paddings are now:

`small`  12, 6 (left/right, top/bottom)
`regular` ~16, 10~ => 12, 10
`large` 20, 12

Eli and I chatted a bit and think `small` is mostly valuable for its height reduction, so it's okay for it to have the same width as `regular`. Ken is doing a bit more detailed spacing audit he'll share with everyone, so can revisit after that if need be.

image

**Comment by stefhatcher** [comment]
@williaster just want to confirm, are the other designers cool with **all** regular buttons being reduced this way?

**Comment by williaster** [comment]
@stefhatcher I'm confirming with other designers now 👍

**Comment by milesj** [comment]
Danger run resulted in 1 warning; to find out more, see the [checks page](https://github.com/airbnb/lunar/runs/98530358).
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f54c80de3187b7b51c05a20b8a8b8d7fa5e6b910
</p>

**Comment by williaster** [comment]
gonna hold off on merging this until after design review (Eli/Danks syncing Fri I think)

**Comment by stefhatcher** [comment]
> gonna hold off on merging this until after design review (Eli/Danks syncing Fri I think)

sounds good @williaster ! does the design review also include pdx folks?

**Comment by elibrumbaugh** [comment]
@stefhatcher Tyler is on the invite as the Support Products rep

**Comment by stefhatcher** [comment]
@elibrumbaugh great! 🎉

**Comment by jpdanks** [comment]
## Resolution
Small, default, and large should have padding consistency with themselves but not across each other.
Updating to `default` to `12px` horizontal and updating `small` to `10px`

button update

## Level of Support
2: Full acceptance, Positive feedback

#### Additional Context:
This breaks data's use case of default inputs with small buttons but agreed that's okay.

## Next Steps
Chris to update code, Danks to document and update figma.
Danks to follow up with Ben on large use cases and support.

#### Exceptions
None.

**Comment by milesj** [comment]
@williaster Can you rebase this? Is this good to go?

**Comment by williaster** [comment]
sorry was on PTO, will rebase. 

and to clarify, @jpdanks I need to update this to make small buttons have `10px` left/right? then the total changes will be:

*`buttons`*
small ~`12, 6`~ => `10, 6` (left/right, top/bottom)
regular ~`16, 10`~ => `12, 10`
large `20, 12` (no change)

*`input`*
decrease `Input` left/right padding from `16px => 12px`

*`Menu.Item`*
increases `Menu.Item` left/right padding from `8px => 12px`

**Comment by milesj** [comment]
Danger run resulted in 1 warning; to find out more, see the [checks page](https://github.com/airbnb/lunar/runs/107952451).
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 5fc58fc2201015e4c7f8304c6df1989663985c41
</p>

**Comment by williaster** [comment]
Updated small button. This should be good to go 👍 

**before**


**after**

**Pull request merged**
