### PR TITLE
misc(AccordionItem): Add test condition in order to bump release version

### PR DESCRIPTION
**Pull request by Tgeo**
to: @milesj @stefhatcher @hayes @alecklandgraf

## Description

Add a small test condition in order to bump `@airbnb/lunar` (core) package version (patch increase).

## Motivation and Context

I got stuck in some kind of Travis CI race condition with another pull request and the `2.29.0` version that exists does _not_ have my changes from this PR https://github.com/airbnb/lunar/pull/189

There is additional discussion in slack if needed.

## Testing

`yarn run jest`

## Screenshots

N/A

## Checklist

- My code follows the style guide of this project.
- I have updated or added documentation accordingly.
- I have read the CONTRIBUTING document.

### CODE REVIEW

**Comment by Tgeo** [comment]
Let me know if changing _only_ test code will result in a release not being created... I can edit some docs or something.

**Comment by stefhatcher** [comment]
not sure! let's give it a try

**Comment by stefhatcher** [comment]
hrmm weird that happo is reporting the `noSpacing` variant as deleted...

**Comment by stefhatcher** [comment]
can you rebase your branch with lunar master?

**Comment by stefhatcher** [comment]
not seeing the `noSpacing` option on your branch for this PR: https://github.com/Tgeo/lunar/blob/tgeonetta--add-test-check/packages/core/src/components/Accordion/Item.tsx

so, that's probably why the happo variant is deleted

**Comment by Tgeo** [comment]
@stefhatcher great catch!! - updated

**Pull request merged**
